"""Initial Model

Revision ID: 6f9c90f3c80d
Revises: 
Create Date: 2024-08-28 12:03:46.554520

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f9c90f3c80d"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_index(
        op.f("ix_application_created_at"), "application", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_application_domain"), "application", ["domain"], unique=False
    )
    op.create_index(op.f("ix_application_name"), "application", ["name"], unique=False)
    op.create_index(op.f("ix_application_uid"), "application", ["uid"], unique=True)
    op.create_table(
        "business",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_index(
        op.f("ix_business_created_at"), "business", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_business_domain"), "business", ["domain"], unique=True)
    op.create_index(op.f("ix_business_name"), "business", ["name"], unique=True)
    op.create_index(op.f("ix_business_uid"), "business", ["uid"], unique=True)
    op.create_table(
        "proposal",
        sa.Column("issuer_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("participants", sa.JSON(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("business_name", sa.String(), nullable=False),
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_index(
        op.f("ix_proposal_business_name"), "proposal", ["business_name"], unique=False
    )
    op.create_index(
        op.f("ix_proposal_created_at"), "proposal", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_proposal_issuer_id"), "proposal", ["issuer_id"], unique=False
    )
    op.create_index(op.f("ix_proposal_status"), "proposal", ["status"], unique=False)
    op.create_index(op.f("ix_proposal_uid"), "proposal", ["uid"], unique=True)
    op.create_index(op.f("ix_proposal_user_id"), "proposal", ["user_id"], unique=False)
    op.create_table(
        "wallet",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("business_name", sa.String(), nullable=False),
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_index(
        op.f("ix_wallet_business_name"), "wallet", ["business_name"], unique=False
    )
    op.create_index(
        op.f("ix_wallet_created_at"), "wallet", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_wallet_uid"), "wallet", ["uid"], unique=True)
    op.create_index(op.f("ix_wallet_user_id"), "wallet", ["user_id"], unique=False)
    op.create_table(
        "permission",
        sa.Column("app_id", sa.Uuid(), nullable=False),
        sa.Column("write_access", sa.Boolean(), nullable=False),
        sa.Column("business_name", sa.String(), nullable=False),
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["app_id"],
            ["application.uid"],
        ),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_index(
        op.f("ix_permission_app_id"), "permission", ["app_id"], unique=False
    )
    op.create_index(
        op.f("ix_permission_business_name"),
        "permission",
        ["business_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_permission_created_at"), "permission", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_permission_uid"), "permission", ["uid"], unique=True)
    op.create_table(
        "transaction",
        sa.Column("proposal_id", sa.Uuid(), nullable=False),
        sa.Column("wallet_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("balance", sa.Numeric(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("business_name", sa.String(), nullable=False),
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["proposal.uid"],
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallet.uid"],
        ),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_index(
        op.f("ix_transaction_business_name"),
        "transaction",
        ["business_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transaction_created_at"), "transaction", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_transaction_currency"), "transaction", ["currency"], unique=False
    )
    op.create_index(
        op.f("ix_transaction_proposal_id"), "transaction", ["proposal_id"], unique=False
    )
    op.create_index(op.f("ix_transaction_uid"), "transaction", ["uid"], unique=True)
    op.create_index(
        op.f("ix_transaction_user_id"), "transaction", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_transaction_wallet_id"), "transaction", ["wallet_id"], unique=False
    )
    op.create_table(
        "wallethold",
        sa.Column("wallet_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", "SUSPENDED", name="statusenum"),
            nullable=False,
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("business_name", sa.String(), nullable=False),
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallet.uid"],
        ),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_index(
        op.f("ix_wallethold_business_name"),
        "wallethold",
        ["business_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_wallethold_created_at"), "wallethold", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_wallethold_expires_at"), "wallethold", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_wallethold_status"), "wallethold", ["status"], unique=False
    )
    op.create_index(op.f("ix_wallethold_uid"), "wallethold", ["uid"], unique=True)
    op.create_index(
        op.f("ix_wallethold_user_id"), "wallethold", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_wallethold_wallet_id"), "wallethold", ["wallet_id"], unique=False
    )
    op.create_table(
        "transactionnote",
        sa.Column("transaction_id", sa.Uuid(), nullable=False),
        sa.Column("note", sa.String(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("business_name", sa.String(), nullable=False),
        sa.Column("uid", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("meta_data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transaction.uid"],
        ),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_index(
        op.f("ix_transactionnote_business_name"),
        "transactionnote",
        ["business_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactionnote_created_at"),
        "transactionnote",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactionnote_transaction_id"),
        "transactionnote",
        ["transaction_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactionnote_uid"), "transactionnote", ["uid"], unique=True
    )
    op.create_index(
        op.f("ix_transactionnote_user_id"), "transactionnote", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactionnote_user_id"), table_name="transactionnote")
    op.drop_index(op.f("ix_transactionnote_uid"), table_name="transactionnote")
    op.drop_index(
        op.f("ix_transactionnote_transaction_id"), table_name="transactionnote"
    )
    op.drop_index(op.f("ix_transactionnote_created_at"), table_name="transactionnote")
    op.drop_index(
        op.f("ix_transactionnote_business_name"), table_name="transactionnote"
    )
    op.drop_table("transactionnote")
    op.drop_index(op.f("ix_wallethold_wallet_id"), table_name="wallethold")
    op.drop_index(op.f("ix_wallethold_user_id"), table_name="wallethold")
    op.drop_index(op.f("ix_wallethold_uid"), table_name="wallethold")
    op.drop_index(op.f("ix_wallethold_status"), table_name="wallethold")
    op.drop_index(op.f("ix_wallethold_expires_at"), table_name="wallethold")
    op.drop_index(op.f("ix_wallethold_created_at"), table_name="wallethold")
    op.drop_index(op.f("ix_wallethold_business_name"), table_name="wallethold")
    op.drop_table("wallethold")
    op.drop_index(op.f("ix_transaction_wallet_id"), table_name="transaction")
    op.drop_index(op.f("ix_transaction_user_id"), table_name="transaction")
    op.drop_index(op.f("ix_transaction_uid"), table_name="transaction")
    op.drop_index(op.f("ix_transaction_proposal_id"), table_name="transaction")
    op.drop_index(op.f("ix_transaction_currency"), table_name="transaction")
    op.drop_index(op.f("ix_transaction_created_at"), table_name="transaction")
    op.drop_index(op.f("ix_transaction_business_name"), table_name="transaction")
    op.drop_table("transaction")
    op.drop_index(op.f("ix_permission_uid"), table_name="permission")
    op.drop_index(op.f("ix_permission_created_at"), table_name="permission")
    op.drop_index(op.f("ix_permission_business_name"), table_name="permission")
    op.drop_index(op.f("ix_permission_app_id"), table_name="permission")
    op.drop_table("permission")
    op.drop_index(op.f("ix_wallet_user_id"), table_name="wallet")
    op.drop_index(op.f("ix_wallet_uid"), table_name="wallet")
    op.drop_index(op.f("ix_wallet_created_at"), table_name="wallet")
    op.drop_index(op.f("ix_wallet_business_name"), table_name="wallet")
    op.drop_table("wallet")
    op.drop_index(op.f("ix_proposal_user_id"), table_name="proposal")
    op.drop_index(op.f("ix_proposal_uid"), table_name="proposal")
    op.drop_index(op.f("ix_proposal_status"), table_name="proposal")
    op.drop_index(op.f("ix_proposal_issuer_id"), table_name="proposal")
    op.drop_index(op.f("ix_proposal_created_at"), table_name="proposal")
    op.drop_index(op.f("ix_proposal_business_name"), table_name="proposal")
    op.drop_table("proposal")
    op.drop_index(op.f("ix_business_uid"), table_name="business")
    op.drop_index(op.f("ix_business_name"), table_name="business")
    op.drop_index(op.f("ix_business_domain"), table_name="business")
    op.drop_index(op.f("ix_business_created_at"), table_name="business")
    op.drop_table("business")
    op.drop_index(op.f("ix_application_uid"), table_name="application")
    op.drop_index(op.f("ix_application_name"), table_name="application")
    op.drop_index(op.f("ix_application_domain"), table_name="application")
    op.drop_index(op.f("ix_application_created_at"), table_name="application")
    op.drop_table("application")
    # ### end Alembic commands ###
